// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtpRI0YY2pBwVVqG6G6RNry4hpZWZ7zCo',
    appId: '1:1068687391641:web:5036856c42b22cac863108',
    messagingSenderId: '1068687391641',
    projectId: 'airplane-aa34c',
    authDomain: 'airplane-aa34c.firebaseapp.com',
    storageBucket: 'airplane-aa34c.appspot.com',
    measurementId: 'G-LJBJVRSN1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeGT_LOSLwyE2pveFgBm-LUpb-OCMiKeI',
    appId: '1:1068687391641:android:c5fe2cf759d5a74d863108',
    messagingSenderId: '1068687391641',
    projectId: 'airplane-aa34c',
    storageBucket: 'airplane-aa34c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOaAemNmOhBwMfLt_1GYuhZDOOkiD1w7E',
    appId: '1:1068687391641:ios:51c999a1dd3a6317863108',
    messagingSenderId: '1068687391641',
    projectId: 'airplane-aa34c',
    storageBucket: 'airplane-aa34c.appspot.com',
    iosBundleId: 'com.example.airplane',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOaAemNmOhBwMfLt_1GYuhZDOOkiD1w7E',
    appId: '1:1068687391641:ios:51c999a1dd3a6317863108',
    messagingSenderId: '1068687391641',
    projectId: 'airplane-aa34c',
    storageBucket: 'airplane-aa34c.appspot.com',
    iosBundleId: 'com.example.airplane',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtpRI0YY2pBwVVqG6G6RNry4hpZWZ7zCo',
    appId: '1:1068687391641:web:26befa1fff754fc6863108',
    messagingSenderId: '1068687391641',
    projectId: 'airplane-aa34c',
    authDomain: 'airplane-aa34c.firebaseapp.com',
    storageBucket: 'airplane-aa34c.appspot.com',
    measurementId: 'G-8YHEDNSTSZ',
  );

}